### ISSUE TITLE
Add two more iframes to ethindia.co/livestream

### ISSUE THREAD

**Issue by chrishobcroft** [ETHIndia/ETHIndia#22]
For ETHIndia hackathon, Livepeer will attempt a world-first... 3 concurrent livestreams on Livepeer from the same event... all embedded on the same page...

So, this issue is to add the following iframes to ethindia.co/livestream (with appropriate spacing)

```
<iframe width="854" height="480" src="https://media.livepeer.org/embed/0xcafa695c965e5b143341376185e13e03f17788a3/?maxWidth=100%&aspectRatio=16:9"></iframe>
```

```
<iframe width="854" height="480" src="https://media.livepeer.org/embed/0xa14f8740d6af9e4ad1a37b74f94d733caf601c1e/?maxWidth=100%&aspectRatio=16:9"></iframe>
```

All 3 livestreams would start automatically, but with the sound muted, and users could choose which stream to "unmute"

Maybe @rahulrumalla might be interested? And @apollonian11 stand by :)

**Comment by rahulrumalla** [comment]
Spoke to Chris. I'm on it.

**Comment by chrishobcroft** [comment]
Also, please could you put some text at the bottom of the page:

Livestreams powered by [Livepeer](http://livepeer.org) - the livestreaming component of the Web 3.0 infrastructure stack.

**Comment by chrishobcroft** [comment]
@apollonian11 are you able to push the new version to the site, with the 3 streams embedded? @shaktigoap

**Comment by apollonian11** [comment]
@chrishobcroft Yes! I'll check this out, and then merge to master.

**Comment by apollonian11** [comment]
@chrishobcroft Deployed
